# configuration file for Weston Qlocky

[core]
require-input=false
idle-time=0
# shell=kiosk-shell.so   # enables fullscreen mode for app

[shell]
background-color=0xff002244
clock-format=seconds

[output]
name=HDMI-A-1
mode=1080x1920
transform=rotate-90

# [autolaunch]
# path=/usr/bin/QlockyApp
# watch=false